yuce/pyswip

README
This reverts commit 1cb2ccad1cd717640609bf044249ee3a7480c773.
This shouldn't be included, as stated in #2.
=> Revert "Add 'disclaimer' to README"

README.md
A fix for [Issue #18](https://github.com/yuce/pyswip/issues/18)
`assertz` now has the correct arity of 1 and `call` is imported
I also added prolog.consult example, a core function that is very useful.  I believe this will help beginners using the library.
I also changed all prints to Python3, with brackets as the library now supports Python3
=> Corrections and Updates

pyswip/core.py
I followed by @rylanchiu here https://github.com/yuce/pyswip/issues/35#issue-331136546 when having errors with the MacOS installation test example. It turns out there were missing hyphens in the arguments to the Popen for swipl. Now that example works for me.
=> Bugfix on core.py

pyswip/prolog.py
Fixes #66 
In the latest versions the cli parameter is changed from 
-nosignal to --no-signals
**EDIT**: The proper parameter is --nosignals
=> Update nosignal cli parameter to fix latest swipl support

pyswip/core.py, pyswip/easy.py, pyswip/prolog.py, tests/test_issues.py, tests/test_unicode.pl
* pyswip/core.py: Add functions required to work with UTF-8 encoded symbols.
* pyswip/easy.py (`Atom.__init__`): Use `PL_atom_wchars` to get string representation of the atom. Unfortunately `PL_atom_wchars` can fail on some strings. e.g. second definition of `father` predicate from https://github.com/Hefaist/test_pyswip/blob/master/utf_facts.pl leads to "ValueError: character U+ffffffe1 is not in range [U+0000; U+10ffff]" error. Allow to pass correct string instead as a workaround.
(`Atom.fromTerm`): Pass atom string representation extracted from `term_t` to Atom constructor.
(`Variable.__init__`): Ask for a UTF-8 string.
(`getAtomChars`): Ask for a UTF-8 string. Remove "deprecated" comment still this function required for `Atom.fromTerm` function.
(`getString`): Ask for a UTF-8 string.
* …
=> Support multibyte strings and atoms

.gitignore, .travis.yml, CHANGELOG.md, CONTRIBUTORS.txt, README.md, pyswip/core.py, setup.py, tests/test_prolog.py
PL_STRING has changed in SWI-Prolog.h.
* Synchronized type constants with SWI-Prolog.h
update for broken compatibility changes in SWI-Prolog.h.
Update to swi-prolog >= 0.8.2 is required (and the default apt
for Ubuntu >= 14.04).
* Fix incorrect REP_* constants.  
* Fixed https://github.com/yuce/pyswip/issues/92 (C assert)
* Fixed https://github.com/yuce/pyswip/issues/90 (quoted string)
=> Compat8.2.0

pyswip/core.py
Enabling MacOS to find libswipl.dylib for any version of swipl (also fixing the fallback directory searching mechanism since the swipl version number is not part of the path).
=> Prologrules macos patch 1

pyswip/core.py
For SWI-Prolog v7.x.x, PLSOEXT reported `dylib`. However, for v8.x.x, this is reported as `so`. 
On MacOS, `so` is reserved for _modules_ (like e.g. `prolog_stream.so`, `json.so`, `tex.so` in `...libexec/lib/swipl/lib/<arch>/`). Dynamic libraries _always_ have the extending `dylib`.
This should be hardcoded in. Currently, if you have SWI-Prolog 8.x.x on MacOS, it will not be able to find `libswipl.dylib` and ask for input for the version number. It _does_ find the SWI home path, but it is unable to find the library because it is erroneously looking for `libswipl.so`.
=> For SWI-Prolog 8 and onward, PLSOEXT usage is erroneous on MacOS.

CONTRIBUTORS.txt, pyswip/core.py, pyswip/easy.py, pyswip/prolog.py, tests/test_prolog.py
Hello,
we have been using this library at Magazino GmbH for quite a while now and made some improvements on top of it. 
We would like to contribute back, hence this PR. 
Changes:
- Improved list representation
- Solved an issue with pyswip, which was segfaulting when multiple threads were using the lib
- Add unicode support for python 2
=> Improve list representations, unicode support and multiple threading usage

pyswip/easy.py, tests/test_examples.py
I discovered a problem when running pyswip on Python 2.7. I get the following error:
pyswip.easy.ArgumentTypeError: Expected an argument of type '("<class 'pyswip.easy.Term'>", "<type 'int'>")' but got '<type 'long'>
This problem is also discussed in https://github.com/yuce/pyswip/issues/40 but the proposed solution is not working, in my case.
I'm running Python 2.7 64bit in combination with SWI-Prolog 64 bit. The problem seems that the integers from the 64bit native library are represented as long in Python 2.7. This is not a problem in Python 3, as int and long are combined in one common datatype.
The workaround for backwards compatibility is adapted from http://python3porting.com/differences.html
I tested the code with 64bit SWI Prolog 8.2.1 on both Python 2.7.16 (64bit) and Python …
=> Backwards compability for Python 2 64bit

pyswip/__init__.py, pyswip/core.py, pyswip/easy.py, pyswip/prolog.py, tests/test_examples.py, tests/test_foreign.py
I created additional support for strings and nested lists in pyswip foreign predicates.
- pyswip foreign predicates now distinguishes between strings and atoms when unifying.
- pyswip foreign predicates can now unify lists of lists (recursive).
- Lists are now unified in a way such that the list can be correctly accessed using the getter method of pyswip.Variable
- It is now possible to register a foreign predicate in a specific module.
I also added tests under test_foreign.py. The tests run successfully with SWI Prolog 8.2.1 and Python 2.7.16 (31bit)
=> Improved handling of lists, nested lists, strings, and atoms

pyswip/core.py
As of version 9.0.1/9.1.1, SWI-Prolog can tell where the shared object lives.  This works reliably on Windows, MacOS and Linux and any other system providing dladdr().   On other systems it uses the value derived from the CMake install configuration and may be wrong if the installation
is relocated.
=> Find libswipl.so from `swipl --dump-runtime-variables`

CONTRIBUTORS.txt, pyswip/core.py
`PL_version` was renamed to `PL_version_info` in SWI-Prolog due to [Exported symbol PL_version conflicts with symbol in Perl](https://github.com/SWI-Prolog/swipl-devel/issues/900).
I noticed that this change resulted in a crash in PySwip, and opened [swipl-devel #910](https://github.com/SWI-Prolog/swipl-devel/issues/910). 
After reviewing the notes added to that issue by @dgelessus, I decided to open this PR with a fix.
> Jan recently had to rename SWI's PL_version function to PL_version_info, to avoid a name conflict with Perl - see #900 for the full context.
>
> It looks like PySwip tries to access the PL_version function, and if it can't find it, it assumes SWI-Prolog 7. With the recent renaming, PL_version doesn't exist anymore, so PySwip is misdetecting SWI-Prolog 8.5 as version 7. …
=> Support SWI-Prolog versions > 8.5.2

CONTRIBUTORS.txt, pyswip/core.py
Before this patch it would not find libswipl.so because in my installation there were two libs:
1. libswipl.so.8.4.3
2. libswipl.so.8 (which is a symlink to the first)
Happened on Fedora 37 using python 3.11 and swipl 8.4.3
=> Fixed not finding swipl lib file when there are multiple options

pyswip/core.py
The path added was where the so file was found when installing from swi-prolog/stable apt repo on __Ubuntu 18.04__
=> Added hardcoded path for libswipl.so

pyswip/core.py
On nixos the libswipl.so is not there, where pyswip could find it. 
Output of `swipl --dump-runtime-variables`:
```
PLBASE="/nix/store/jlik9111a3hmfs6q5bwd7fnkyzdh08yf-swi-prolog-8.1.15/lib/swipl";
PLARCH="x86_64-linux";
PLBITS="64";
PLVERSION="80115";
PLSOEXT="so";
PLSOPATH="LD_LIBRARY_PATH";
PLLIBDIR="/nix/store/jlik9111a3hmfs6q5bwd7fnkyzdh08yf-swi-prolog-8.1.15/lib/swipl/lib/x86_64-linux";
PLLIB="-lswipl";
PLSHARED="yes";
PLTHREADS="yes";
```
but the shared lib is here:
`/nix/store/jlik9111a3hmfs6q5bwd7fnkyzdh08yf-swi-prolog-8.1.15/lib/libswipl.so.8`
pyswip would expect it under $PLBASE/$PLARCH
swi-prolog on nixos is build with the flag -DSWIPL_INSTALL_IN_LIB=ON
one idea is to use a new environment variable, like in my patch. What do you think?
=> use LIBSWIPL_PATH from environment

CONTRIBUTORS.txt, pyswip/core.py
In older versions of libswipl.so, pyswip produced this error:
```
Traceback (most recent call last):                                                                       
File "/home/omf/.local/lib/python3.10/site-packages/pyswip/core.py", line 597, in <module>
if _lib.PL_version_info != None:                                                                     
File "/usr/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__                                
func = self.__getitem__(name)                                                                        
File "/usr/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
func = self._FuncPtr((name_or_ordinal, self))                                                        
AttributeError: /lib/libswipl.so.8: undefined symbol: …
```
=> Avoid AttributeError with PL_version_info in swipl <= 8.4.2

pyswip/core.py, pyswip/prolog.py, tests/test_prolog.py
In this PR, I have added the method for aborting a query. Also, I have added the handling of an exception that popped up on our side during cleanup.
=> Add abort functionality and handle exception in cleanup

README.md, examples/coins/coins.py, examples/coins/coins_new.py, examples/draughts/puzzle1.py, examples/hanoi/hanoi.py, examples/sendmoremoney/money.py, examples/sendmoremoney/money_new.py, src/pyswip/__init__.py, src/pyswip/core.py, src/pyswip/easy.py, src/pyswip/prolog.py, src/pyswip/utils.py, tests/test_issues.py, tests/test_prolog.py, tests/test_utils.py
This PR contains several enhancements to the `Prolog.consult` method.
```python
Prolog.consult("~/my_files/hanoi.pl")
```
```python
from pathlib import Path
Prolog.consult(Path("myfile.pl"))
Prolog.consult("myfile.pl")
```
`relative_to` keyword argument makes it easier to construct the consult path.
This keyword is no-op, if the consult path is absolute.
If the given `relative_to` path is a file, then the consult path is updated to become a sibling of that path.
Assume you have the `/home/me/project/facts.pl` that you want to consult from the `run.py` file which exists in the same directory `/home/me/project`.
Using the built-in `__file__` constant which contains the path of the current Python file , it becomes very easy to do that:
```python
Prolog.consult("facts.pl", …
```
=> Prolog.consult method updates

.github/workflows/tests.yaml, CONTRIBUTORS.txt, src/pyswip/prolog.py
Fixed #193 .
- Resolved the path problem with consult method. Now the path is considered as POSIX. 
- Added Windows in the os matrix in test.yaml.
The problem with the backward compatibility is still present.
=> Problem with Path
